// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"sonar-bat/ent/predicate"
	"sonar-bat/ent/rbacobject"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RbacObjectDelete is the builder for deleting a RbacObject entity.
type RbacObjectDelete struct {
	config
	hooks    []Hook
	mutation *RbacObjectMutation
}

// Where appends a list predicates to the RbacObjectDelete builder.
func (rod *RbacObjectDelete) Where(ps ...predicate.RbacObject) *RbacObjectDelete {
	rod.mutation.Where(ps...)
	return rod
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (rod *RbacObjectDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, rod.sqlExec, rod.mutation, rod.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (rod *RbacObjectDelete) ExecX(ctx context.Context) int {
	n, err := rod.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (rod *RbacObjectDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(rbacobject.Table, sqlgraph.NewFieldSpec(rbacobject.FieldID, field.TypeUUID))
	if ps := rod.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, rod.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	rod.mutation.done = true
	return affected, err
}

// RbacObjectDeleteOne is the builder for deleting a single RbacObject entity.
type RbacObjectDeleteOne struct {
	rod *RbacObjectDelete
}

// Where appends a list predicates to the RbacObjectDelete builder.
func (rodo *RbacObjectDeleteOne) Where(ps ...predicate.RbacObject) *RbacObjectDeleteOne {
	rodo.rod.mutation.Where(ps...)
	return rodo
}

// Exec executes the deletion query.
func (rodo *RbacObjectDeleteOne) Exec(ctx context.Context) error {
	n, err := rodo.rod.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{rbacobject.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (rodo *RbacObjectDeleteOne) ExecX(ctx context.Context) {
	if err := rodo.Exec(ctx); err != nil {
		panic(err)
	}
}
