auth:
  jwt:
    secret: "${JWT_SECRET:PlsChangeMe}"
    expiration: 3600s
  oauth:
    google_client_id: "${GOOGLE_CLIENT_ID:PlsChangeMe}"
    google_client_secret: "${GOOGLE_CLIENT_SECRET:PlsChangeMe}"
    google_redirect_url: "${GOOGLE_REDIRECT_URL:PlsChangeMe}"
    github_client_id: "${GITHUB_CLIENT_ID:PlsChange}"
    github_client_secret: "${GITHUB_CLIENT_SECRET:PlsChange}"
    github_redirect_url: "${GITHUB_REDIRECT_URL:PlsChangeMe}"