// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Dictionary is the predicate function for dictionary builders.
type Dictionary func(*sql.Selector)

// Host is the predicate function for host builders.
type Host func(*sql.Selector)

// HostBlacklist is the predicate function for hostblacklist builders.
type HostBlacklist func(*sql.Selector)

// RbacObject is the predicate function for rbacobject builders.
type RbacObject func(*sql.Selector)

// RbacPolicy is the predicate function for rbacpolicy builders.
type RbacPolicy func(*sql.Selector)

// RbacRole is the predicate function for rbacrole builders.
type RbacRole func(*sql.Selector)

// Subtask is the predicate function for subtask builders.
type Subtask func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)

// Token is the predicate function for token builders.
type Token func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
